<?php

use Illuminate\Database\Seeder;

class KabupatenTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        // //remove any existing data in provinsi table
        // DB::table('kabupaten')->delete();
        
        $data =
        [
            ['id_kabupaten'=>   1   , 'nama_kabupaten' => 'Aceh Selatan', 'provinsi_id_provinsi'    =>  11],
            ['id_kabupaten'=>   2   , 'nama_kabupaten' => 'Simeulue    ', 'provinsi_id_provinsi'    =>  11],
            ['id_kabupaten'=>   3   , 'nama_kabupaten' => 'Aceh Tenggara', 'provinsi_id_provinsi'   =>  11],
            ['id_kabupaten'=>   4   , 'nama_kabupaten' => 'Aceh Timur', 'provinsi_id_provinsi'      =>  11],
            ['id_kabupaten'=>   5   , 'nama_kabupaten' => 'Aceh Tengah', 'provinsi_id_provinsi'     =>  11],
            ['id_kabupaten'=>   6   , 'nama_kabupaten' => 'Aceh Barat', 'provinsi_id_provinsi'      =>  11],
            ['id_kabupaten'=>   7   , 'nama_kabupaten' => 'Aceh Besar', 'provinsi_id_provinsi'      =>  11],
            ['id_kabupaten'=>   8   , 'nama_kabupaten' => 'Pidie   ', 'provinsi_id_provinsi'        =>  11],
            ['id_kabupaten'=>   9   , 'nama_kabupaten' => 'Aceh Utara', 'provinsi_id_provinsi'      =>  11],
            ['id_kabupaten'=>   10  , 'nama_kabupaten' => 'Simeulue      ', 'provinsi_id_provinsi'  =>  11],
            ['id_kabupaten'=>   11  , 'nama_kabupaten' => 'Aceh Singkil', 'provinsi_id_provinsi'    =>  11],
            ['id_kabupaten'=>   12  , 'nama_kabupaten' => 'Bireuen ', 'provinsi_id_provinsi'        =>  11],
            ['id_kabupaten'=>   13  , 'nama_kabupaten' => 'Aceh BaratDaya', 'provinsi_id_provinsi'  =>  11],
            ['id_kabupaten'=>   14  , 'nama_kabupaten' => 'Gayo Lues', 'provinsi_id_provinsi'       =>  11],
            ['id_kabupaten'=>   15  , 'nama_kabupaten' => 'Aceh Jaya', 'provinsi_id_provinsi'       =>  11],
            ['id_kabupaten'=>   16  , 'nama_kabupaten' => 'Nagan Raya', 'provinsi_id_provinsi'      =>  11],
            ['id_kabupaten'=>   17  , 'nama_kabupaten' => 'Aceh Tamiang', 'provinsi_id_provinsi'    =>  11],
            ['id_kabupaten'=>   18  , 'nama_kabupaten' => 'Aceh Jaya', 'provinsi_id_provinsi'       =>  11],
            ['id_kabupaten'=>   19  , 'nama_kabupaten' => 'Bener Meriah', 'provinsi_id_provinsi'    =>  11],
            ['id_kabupaten'=>   20  , 'nama_kabupaten' => 'Pidie Jaya', 'provinsi_id_provinsi'      =>  11],
            ['id_kabupaten'=>   21  , 'nama_kabupaten' => 'Kota Banda Aceh ', 'provinsi_id_provinsi'=>  11], 
            ['id_kabupaten'=>   22  , 'nama_kabupaten' => 'Kota Sabang', 'provinsi_id_provinsi'     =>  11],
            ['id_kabupaten'=>   23  , 'nama_kabupaten' => 'Kota Lhokseumawe', 'provinsi_id_provinsi'=>  11],
            ['id_kabupaten'=>   24  , 'nama_kabupaten' => 'Kota Langsa', 'provinsi_id_provinsi'     =>  11],
            ['id_kabupaten'=>   25  , 'nama_kabupaten' => 'Kota Subulussalam', 'provinsi_id_provinsi'=> 11],
            ['id_kabupaten'=>   26  , 'nama_kabupaten' => 'Tapanuli Tengah', 'provinsi_id_provinsi' =>  12],
            ['id_kabupaten'=>   27  , 'nama_kabupaten' => 'Tapanuli Utara', 'provinsi_id_provinsi'  =>  12],
            ['id_kabupaten'=>   28  , 'nama_kabupaten' => 'Tapanuli Selatan', 'provinsi_id_provinsi'=>  12],
            ['id_kabupaten'=>   29  , 'nama_kabupaten' => 'Nias    ', 'provinsi_id_provinsi'        =>  12],
            ['id_kabupaten'=>   30  , 'nama_kabupaten' => 'Langkat ', 'provinsi_id_provinsi'        =>  12],
            ['id_kabupaten'=>   31  , 'nama_kabupaten' => 'Karo    ', 'provinsi_id_provinsi'        =>  12],
            ['id_kabupaten'=>   32  , 'nama_kabupaten' => 'Deli Serdang', 'provinsi_id_provinsi'    =>  12],
            ['id_kabupaten'=>   33  , 'nama_kabupaten' => 'Simalungun  ', 'provinsi_id_provinsi'    =>  12],
            ['id_kabupaten'=>   34  , 'nama_kabupaten' => 'Asahan  ', 'provinsi_id_provinsi'        =>  12],
            ['id_kabupaten'=>   35  , 'nama_kabupaten' => 'Labuhan Batu', 'provinsi_id_provinsi'    =>  12],
            ['id_kabupaten'=>   36  , 'nama_kabupaten' => 'Dairi   ', 'provinsi_id_provinsi'        =>  12],
            ['id_kabupaten'=>   37  , 'nama_kabupaten' => 'Toba Samosir', 'provinsi_id_provinsi' =>     12],
            ['id_kabupaten'=>   38  , 'nama_kabupaten' => 'Mandailing Natal', 'provinsi_id_provinsi' => 12],
            ['id_kabupaten'=>   39  , 'nama_kabupaten' => 'Nias Selatan', 'provinsi_id_provinsi' =>     12],
            ['id_kabupaten'=>   40  , 'nama_kabupaten' => 'Pakpak Bharat', 'provinsi_id_provinsi' =>    12],
            ['id_kabupaten'=>   41  , 'nama_kabupaten' => 'Humbang Hasundutan', 'provinsi_id_provinsi'=>12],
            ['id_kabupaten'=>   42  , 'nama_kabupaten' => 'Samosir ', 'provinsi_id_provinsi'          =>12],
            ['id_kabupaten'=>   43  , 'nama_kabupaten' => 'Serdang Bedagai', 'provinsi_id_provinsi' =>  12],
            ['id_kabupaten'=>   44  , 'nama_kabupaten' => 'Padang Lawas', 'provinsi_id_provinsi' =>     12],
            ['id_kabupaten'=>   45  , 'nama_kabupaten' => 'Padang Lawas Utara', 'provinsi_id_provinsi'=>12], 
            ['id_kabupaten'=>   46  , 'nama_kabupaten' => 'Batu Bara', 'provinsi_id_provinsi'       =>  12],
            ['id_kabupaten'=>   47  , 'nama_kabupaten' => 'Labuhan Batu Selatan', 'provinsi_id_provinsi'=>12],    
            ['id_kabupaten'=>   48  , 'nama_kabupaten' => 'Labuhan Batu Utara', 'provinsi_id_provinsi' =>12],  
            ['id_kabupaten'=>   49  , 'nama_kabupaten' => 'Nias Barat', 'provinsi_id_provinsi'      =>  12],
            ['id_kabupaten'=>   50  , 'nama_kabupaten' => 'Nias Utara', 'provinsi_id_provinsi'      =>  12],
            ['id_kabupaten'=>   51  , 'nama_kabupaten' => 'Kota Medan', 'provinsi_id_provinsi'      =>  12],
            ['id_kabupaten'=>   52  , 'nama_kabupaten' => 'Kota Pematang Siantar', 'provinsi_id_provinsi'=>12], 
            ['id_kabupaten'=>   53  , 'nama_kabupaten' => 'Kota Sibolga', 'provinsi_id_provinsi' =>    12],
            ['id_kabupaten'=>   54  , 'nama_kabupaten' => 'Kota Tanjung Balai', 'provinsi_id_provinsi'=> 12],
            ['id_kabupaten'=>   55  , 'nama_kabupaten' => 'Kota Binjai', 'provinsi_id_provinsi' => 12],
            ['id_kabupaten'=>   56  , 'nama_kabupaten' => 'Kota Tebing Tinggi', 'provinsi_id_provinsi' => 12], 
            ['id_kabupaten'=>   57  , 'nama_kabupaten' => 'Kota Padangsidimpuan', 'provinsi_id_provinsi' =>12],
            ['id_kabupaten'=>   58  , 'nama_kabupaten' => 'Kota Gunungsitoli', 'provinsi_id_provinsi' => 12],
            ['id_kabupaten'=>   59  , 'nama_kabupaten' => 'Pesisir Selatan', 'provinsi_id_provinsi' => 13],
            ['id_kabupaten'=>   60  , 'nama_kabupaten' => 'Solok ', 'provinsi_id_provinsi'          =>13],
            ['id_kabupaten'=>   61  , 'nama_kabupaten' => 'Sijunjung ', 'provinsi_id_provinsi'      =>13],
            ['id_kabupaten'=>   62  , 'nama_kabupaten' => 'Tanah Datar', 'provinsi_id_provinsi'     => 13],
            ['id_kabupaten'=>   63  , 'nama_kabupaten' => 'Padang Pariaman', 'provinsi_id_provinsi' => 13],
            ['id_kabupaten'=>   64  , 'nama_kabupaten' => 'Agam', 'provinsi_id_provinsi'        =>13],
            ['id_kabupaten'=>   65  , 'nama_kabupaten' => 'Lima Puluh Kota', 'provinsi_id_provinsi' => 13],
            ['id_kabupaten'=>   66  , 'nama_kabupaten' => 'Pasaman ', 'provinsi_id_provinsi'        =>13],
            ['id_kabupaten'=>   67  , 'nama_kabupaten' => 'Kepulauan Mentawai', 'provinsi_id_provinsi'=>  13],
            ['id_kabupaten'=>   68  , 'nama_kabupaten' => 'Dharmasraya ', 'provinsi_id_provinsi' => 13],
            ['id_kabupaten'=>   69  , 'nama_kabupaten' => 'Solok Selatan', 'provinsi_id_provinsi' =>   13],
            ['id_kabupaten'=>   70  , 'nama_kabupaten' => 'Pasaman Barat', 'provinsi_id_provinsi' =>   13],
            ['id_kabupaten'=>   71  , 'nama_kabupaten' => 'Kota Padang', 'provinsi_id_provinsi' => 13],
            ['id_kabupaten'=>   72  , 'nama_kabupaten' => 'Kota Solok', 'provinsi_id_provinsi' =>  13],
            ['id_kabupaten'=>   73  , 'nama_kabupaten' => 'Kota Sawah Lunto', 'provinsi_id_provinsi' => 13],    
            ['id_kabupaten'=>   74  , 'nama_kabupaten' => 'Kota Padang Panjang', 'provinsi_id_provinsi' => 13], 
            ['id_kabupaten'=>   75  , 'nama_kabupaten' => 'Kota Bukittinggi', 'provinsi_id_provinsi' =>    13],
            ['id_kabupaten'=>   76  , 'nama_kabupaten' => 'Kota Payakumbuh', 'provinsi_id_provinsi' => 13],
            ['id_kabupaten'=>   77  , 'nama_kabupaten' => 'Kota Pariaman', 'provinsi_id_provinsi' =>   13],
            ['id_kabupaten'=>   78  , 'nama_kabupaten' => 'Kampar  ', 'provinsi_id_provinsi'        =>14],
            ['id_kabupaten'=>   79  , 'nama_kabupaten' => 'Indragiri Hulu', 'provinsi_id_provinsi' =>  14],
            ['id_kabupaten'=>   80  , 'nama_kabupaten' => 'Bengkalis   ', 'provinsi_id_provinsi' =>   14],
            ['id_kabupaten'=>   81  , 'nama_kabupaten' => 'Indragiri Hilir', 'provinsi_id_provinsi' => 14],
            ['id_kabupaten'=>   82  , 'nama_kabupaten' => 'Pelalawan   ', 'provinsi_id_provinsi' =>14],
            ['id_kabupaten'=>   83  , 'nama_kabupaten' => 'Rokan Hulu', 'provinsi_id_provinsi' =>  14],
            ['id_kabupaten'=>   84  , 'nama_kabupaten' => 'Rokan Hilir', 'provinsi_id_provinsi' => 14],
            ['id_kabupaten'=>   85  , 'nama_kabupaten' => 'Siak    ', 'provinsi_id_provinsi' =>14],
            ['id_kabupaten'=>   86  , 'nama_kabupaten' => 'Kuantan Singingi', 'provinsi_id_provinsi' =>    14],
            ['id_kabupaten'=>   87  , 'nama_kabupaten' => 'Kepulauan Meranti', 'provinsi_id_provinsi' =>   14],
            ['id_kabupaten'=>   88  , 'nama_kabupaten' => 'Kota Pekanbaru', 'provinsi_id_provinsi' =>  14],
            ['id_kabupaten'=>   89  , 'nama_kabupaten' => 'Kota Dumai', 'provinsi_id_provinsi' =>  14],
            ['id_kabupaten'=>   90  , 'nama_kabupaten' => 'Kerinci', 'provinsi_id_provinsi' =>15],
            ['id_kabupaten'=>   91  , 'nama_kabupaten' => 'Merangin ', 'provinsi_id_provinsi' =>15],
            ['id_kabupaten'=>   92  , 'nama_kabupaten' => 'Sarolangun ', 'provinsi_id_provinsi' =>15],
            ['id_kabupaten'=>   93  , 'nama_kabupaten' => 'Batang Hari', 'provinsi_id_provinsi' => 15],
            ['id_kabupaten'=>   94  , 'nama_kabupaten' => 'Muaro Jambi', 'provinsi_id_provinsi' => 15],
            ['id_kabupaten'=>   95  , 'nama_kabupaten' => 'Tanjung Jabung Barat', 'provinsi_id_provinsi' => 15],    
            ['id_kabupaten'=>   96  , 'nama_kabupaten' => 'Tanjung Jabung Timur', 'provinsi_id_provinsi' => 15],    
            ['id_kabupaten'=>   97  , 'nama_kabupaten' => 'Bungo', 'provinsi_id_provinsi'                => 15],
            ['id_kabupaten'=>   98  , 'nama_kabupaten' => 'Tebo    ', 'provinsi_id_provinsi'              =>15],
            ['id_kabupaten'=>   99  , 'nama_kabupaten' => 'Kota Jambi', 'provinsi_id_provinsi'          =>  15],
            ['id_kabupaten'=>   100, 'nama_kabupaten' => 'Kota Sungai Penuh', 'provinsi_id_provinsi'    => 15],
            ['id_kabupaten'=>   101, 'nama_kabupaten' => 'Ogan Komering Ulu', 'provinsi_id_provinsi'    => 16], 
            ['id_kabupaten'=>   102, 'nama_kabupaten' => 'Ogan Komering Ilir', 'provinsi_id_provinsi'   => 16],
            ['id_kabupaten'=>   103, 'nama_kabupaten' => 'Muara Enim', 'provinsi_id_provinsi'           => 16],
            ['id_kabupaten'=>   104, 'nama_kabupaten' => 'Lahat   ', 'provinsi_id_provinsi'             => 16],
            ['id_kabupaten'=>   105, 'nama_kabupaten' => 'Musi Rawas', 'provinsi_id_provinsi'           => 16],
            ['id_kabupaten'=>   106, 'nama_kabupaten' => 'Musi Banyuasin', 'provinsi_id_provinsi'       => 16],
            ['id_kabupaten'=>   107, 'nama_kabupaten' => 'Banyuasin', 'provinsi_id_provinsi'            => 16],
            ['id_kabupaten'=>   108, 'nama_kabupaten' => 'Ogan Komering Ulu Timur', 'provinsi_id_provinsi' => 16], 
            ['id_kabupaten'=>   109, 'nama_kabupaten' => 'Ogan Komering Ulu Selatan', 'provinsi_id_provinsi' => 16], 
            ['id_kabupaten'=>   110, 'nama_kabupaten' => 'Ogan Ilir', 'provinsi_id_provinsi'            => 16],
            ['id_kabupaten'=>   111, 'nama_kabupaten' => 'Empat Lawang', 'provinsi_id_provinsi'         => 16],
            ['id_kabupaten'=>   112, 'nama_kabupaten' => 'Penukal Abab Lematang Ilir', 'provinsi_id_provinsi' => 16], 
            ['id_kabupaten'=>   113, 'nama_kabupaten' => 'Musi Rawas Utara', 'provinsi_id_provinsi'         => 16],
            ['id_kabupaten'=>   114, 'nama_kabupaten' => 'Kota Palembang', 'provinsi_id_provinsi'           => 16],
            ['id_kabupaten'=>   115, 'nama_kabupaten' => 'Kota Pagar Alam', 'provinsi_id_provinsi' => 16], 
            ['id_kabupaten'=>   116, 'nama_kabupaten' => 'Kota Lubuklinggau', 'provinsi_id_provinsi' =>   16],
            ['id_kabupaten'=>   117, 'nama_kabupaten' => 'Kota Prabumulih', 'provinsi_id_provinsi' => 16],
            ['id_kabupaten'=>   118, 'nama_kabupaten' => 'Bengkulu Selatan', 'provinsi_id_provinsi' =>    17],
            ['id_kabupaten'=>   119, 'nama_kabupaten' => 'Rejang Lebong', 'provinsi_id_provinsi' =>   17],
            ['id_kabupaten'=>   120, 'nama_kabupaten' => 'Bengkulu Utara', 'provinsi_id_provinsi' =>  17],
            ['id_kabupaten'=>   121, 'nama_kabupaten' => 'Kaur', 'provinsi_id_provinsi'            =>17],
            ['id_kabupaten'=>   122, 'nama_kabupaten' => 'Seluma  ', 'provinsi_id_provinsi'        => 17],
            ['id_kabupaten'=>   123, 'nama_kabupaten' => 'Mukomuko   ', 'provinsi_id_provinsi'      =>17],
            ['id_kabupaten'=>   124, 'nama_kabupaten' => 'Lebong  ', 'provinsi_id_provinsi'         =>17],          
            ['id_kabupaten'=>   125, 'nama_kabupaten' => 'Kepahiang   ', 'provinsi_id_provinsi' => 17],
            ['id_kabupaten'=>   126, 'nama_kabupaten' => 'Bengkulu Tengah', 'provinsi_id_provinsi' => 17],
            ['id_kabupaten'=>   127, 'nama_kabupaten' => 'Kota Bengkulu', 'provinsi_id_provinsi' =>   17],
            ['id_kabupaten'=>   128, 'nama_kabupaten' => 'Lampung Selatan', 'provinsi_id_provinsi' => 18],
            ['id_kabupaten'=>   129, 'nama_kabupaten' => 'Lampung Tengah', 'provinsi_id_provinsi' =>  18],
            ['id_kabupaten'=>   130, 'nama_kabupaten' => 'Lampung Utara', 'provinsi_id_provinsi' =>   18],
            ['id_kabupaten'=>   131, 'nama_kabupaten' => 'Lampung Barat', 'provinsi_id_provinsi' =>   18],
            ['id_kabupaten'=>   132, 'nama_kabupaten' => 'Tulangbawang ', 'provinsi_id_provinsi'   => 18],
            ['id_kabupaten'=>   133, 'nama_kabupaten' => 'Tanggamus  ', 'provinsi_id_provinsi'   => 18],
            ['id_kabupaten'=>   134, 'nama_kabupaten' => 'Lampung Timur', 'provinsi_id_provinsi' =>  18],
            ['id_kabupaten'=>   135, 'nama_kabupaten' => 'Way Kanan', 'provinsi_id_provinsi' =>   18],
            ['id_kabupaten'=>   136, 'nama_kabupaten' => 'Pesawaran  ', 'provinsi_id_provinsi' => 18],
            ['id_kabupaten'=>   137, 'nama_kabupaten' => 'Pringsewu  ', 'provinsi_id_provinsi' => 18],
            ['id_kabupaten'=>   138, 'nama_kabupaten' => 'Tulang Bawang Barat', 'provinsi_id_provinsi' => 18], 
            ['id_kabupaten'=>   139, 'nama_kabupaten' => 'Mesuji', 'provinsi_id_provinsi'               =>18],
            ['id_kabupaten'=>   140, 'nama_kabupaten' => 'Pesisir Barat', 'provinsi_id_provinsi'        =>18],
            ['id_kabupaten'=>   141, 'nama_kabupaten' => 'Kota Bandar Lampung', 'provinsi_id_provinsi'=> 18], 
            ['id_kabupaten'=>   142, 'nama_kabupaten' => 'Kota Metro', 'provinsi_id_provinsi'        =>  18],
            ['id_kabupaten'=>   143, 'nama_kabupaten' => 'Bangka  ', 'provinsi_id_provinsi'       =>   19],
            ['id_kabupaten'=>   144, 'nama_kabupaten' => 'Belitung    ', 'provinsi_id_provinsi'      =>19],
            ['id_kabupaten'=>   145, 'nama_kabupaten' => 'Bangka Selatan', 'provinsi_id_provinsi' =>  19],
            ['id_kabupaten'=>   146, 'nama_kabupaten' => 'Bangka Tengah', 'provinsi_id_provinsi' =>   19],
            ['id_kabupaten'=>   147, 'nama_kabupaten' => 'Bangka Barat', 'provinsi_id_provinsi' =>    19],
            ['id_kabupaten'=>   148, 'nama_kabupaten' => 'Belitung Timur', 'provinsi_id_provinsi' =>  19],
            ['id_kabupaten'=>   149, 'nama_kabupaten' => 'Kota Pangkal Pinang', 'provinsi_id_provinsi' => 19], 
            ['id_kabupaten'=>   150, 'nama_kabupaten' => 'Bintan  ', 'provinsi_id_provinsi'             =>21],
            ['id_kabupaten'=>   151, 'nama_kabupaten' => 'Karimun ', 'provinsi_id_provinsi'           =>21],
            ['id_kabupaten'=>   152, 'nama_kabupaten' => 'Natuna  ', 'provinsi_id_provinsi'           =>21],
            ['id_kabupaten'=>   153, 'nama_kabupaten' => 'Lingga  ', 'provinsi_id_provinsi'         =>21],
            ['id_kabupaten'=>   154, 'nama_kabupaten' => 'Kepulauan Anambas', 'provinsi_id_provinsi' => 21],
            ['id_kabupaten'=>   155, 'nama_kabupaten' => 'Kota Batam', 'provinsi_id_provinsi' =>  21],
            ['id_kabupaten'=>   156, 'nama_kabupaten' => 'Kota Tanjung Pinang', 'provinsi_id_provinsi' => 21], 
            ['id_kabupaten'=>   157, 'nama_kabupaten' => 'Kepulauan Seribu', 'provinsi_id_provinsi' =>    31],
            ['id_kabupaten'=>   158, 'nama_kabupaten' => 'Kota Jakarta Pusat', 'provinsi_id_provinsi' => 31],  
            ['id_kabupaten'=>   159, 'nama_kabupaten' => 'Kota Jakarta Utara', 'provinsi_id_provinsi' => 31],  
            ['id_kabupaten'=>   160, 'nama_kabupaten' => 'Kota Jakarta Barat', 'provinsi_id_provinsi' => 31],  
            ['id_kabupaten'=>   161, 'nama_kabupaten' => 'Kota Jakarta Selatan', 'provinsi_id_provinsi' =>31],
            ['id_kabupaten'=>   162, 'nama_kabupaten' => 'Kota Jakarta Timur', 'provinsi_id_provinsi' => 31],  
            ['id_kabupaten'=>   163, 'nama_kabupaten' => 'Bogor', 'provinsi_id_provinsi'                =>32],
            ['id_kabupaten'=>   164, 'nama_kabupaten' => 'Sukabumi    ', 'provinsi_id_provinsi'       =>32],
            ['id_kabupaten'=>   165, 'nama_kabupaten' => 'Cianjur ', 'provinsi_id_provinsi'           =>32],
            ['id_kabupaten'=>   166, 'nama_kabupaten' => 'Bandung ', 'provinsi_id_provinsi'           =>32],
            ['id_kabupaten'=>   167, 'nama_kabupaten' => 'Garut   ', 'provinsi_id_provinsi'           =>32],
            ['id_kabupaten'=>   168, 'nama_kabupaten' => 'Tasikmalaya ', 'provinsi_id_provinsi'       =>32],
            ['id_kabupaten'=>   169, 'nama_kabupaten' => 'Ciamis  ', 'provinsi_id_provinsi'           =>32],
            ['id_kabupaten'=>   170, 'nama_kabupaten' => 'Kuningan    ', 'provinsi_id_provinsi'       =>32],
            ['id_kabupaten'=>   171, 'nama_kabupaten' => 'Cirebon ', 'provinsi_id_provinsi'          =>32],
            ['id_kabupaten'=>   172, 'nama_kabupaten' => 'Majalengka', 'provinsi_id_provinsi'   =>32],
            ['id_kabupaten'=>   173, 'nama_kabupaten' => 'Sumedang  ', 'provinsi_id_provinsi'   =>32],
            ['id_kabupaten'=>   174, 'nama_kabupaten' => 'Indramayu ', 'provinsi_id_provinsi'   =>32],
            ['id_kabupaten'=>   175, 'nama_kabupaten' => 'Subang  ', 'provinsi_id_provinsi'       =>32],
            ['id_kabupaten'=>   176, 'nama_kabupaten' => 'Purwakarta', 'provinsi_id_provinsi' =>32],
            ['id_kabupaten'=>   177, 'nama_kabupaten' => 'Karawang ', 'provinsi_id_provinsi' =>32],
            ['id_kabupaten'=>   178, 'nama_kabupaten' => 'Bekasi  ', 'provinsi_id_provinsi' =>32],
            ['id_kabupaten'=>   179, 'nama_kabupaten' => 'Bandung Barat', 'provinsi_id_provinsi' =>   32],
            ['id_kabupaten'=>   180, 'nama_kabupaten' => 'Pangandaran', 'provinsi_id_provinsi' => 32],
            ['id_kabupaten'=>   181, 'nama_kabupaten' => 'Kota Bogor', 'provinsi_id_provinsi' =>  32],
            ['id_kabupaten'=>   182, 'nama_kabupaten' => 'Kota Sukabumi', 'provinsi_id_provinsi' =>32],
            ['id_kabupaten'=>   183, 'nama_kabupaten' => 'Kota Bandung', 'provinsi_id_provinsi' => 32],
            ['id_kabupaten'=>   184, 'nama_kabupaten' => 'Kota Cirebon', 'provinsi_id_provinsi' => 32],
            ['id_kabupaten'=>   185, 'nama_kabupaten' => 'Kota Bekasi', 'provinsi_id_provinsi' => 32],
            ['id_kabupaten'=>   186, 'nama_kabupaten' => 'Kota Depok', 'provinsi_id_provinsi' =>  32],
            ['id_kabupaten'=>   187, 'nama_kabupaten' => 'Kota Cimahi', 'provinsi_id_provinsi' => 32],
            ['id_kabupaten'=>   188, 'nama_kabupaten' => 'Kota Tasikmalaya', 'provinsi_id_provinsi' =>32],
            ['id_kabupaten'=>   189, 'nama_kabupaten' => 'Kota Banjar', 'provinsi_id_provinsi' => 32],
            ['id_kabupaten'=>   190, 'nama_kabupaten' => 'Cilacap', 'provinsi_id_provinsi' =>33],
            ['id_kabupaten'=>   191, 'nama_kabupaten' => 'Banyumas', 'provinsi_id_provinsi' =>33],
            ['id_kabupaten'=>   192, 'nama_kabupaten' => 'Purbalingga', 'provinsi_id_provinsi' =>33],
            ['id_kabupaten'=>   193, 'nama_kabupaten' => 'Banjarnegara', 'provinsi_id_provinsi' =>33],
            ['id_kabupaten'=>   194, 'nama_kabupaten' => 'Kebumen', 'provinsi_id_provinsi' =>33],
            ['id_kabupaten'=>   195, 'nama_kabupaten' => 'Purworejo', 'provinsi_id_provinsi' =>33],
            ['id_kabupaten'=>   196, 'nama_kabupaten' => 'Wonosobo', 'provinsi_id_provinsi' =>33],
            ['id_kabupaten'=>   197, 'nama_kabupaten' => 'Magelang', 'provinsi_id_provinsi' =>33],
            ['id_kabupaten'=>   198, 'nama_kabupaten' => 'Boyolali', 'provinsi_id_provinsi' =>33],
            ['id_kabupaten'=>   199, 'nama_kabupaten' => 'Klaten ', 'provinsi_id_provinsi' =>33],
            ['id_kabupaten'=>   200, 'nama_kabupaten' => 'Sukoharjo ', 'provinsi_id_provinsi' =>33],
            ['id_kabupaten'=>   201, 'nama_kabupaten' => 'Wonogiri  ', 'provinsi_id_provinsi' =>33],
            ['id_kabupaten'=>   202, 'nama_kabupaten' => 'Karanganyar', 'provinsi_id_provinsi' =>33],
            ['id_kabupaten'=>   203, 'nama_kabupaten' => 'Sragen', 'provinsi_id_provinsi' =>33],
            ['id_kabupaten'=>   204, 'nama_kabupaten' => 'Grobogan', 'provinsi_id_provinsi' =>33],
            ['id_kabupaten'=>   205, 'nama_kabupaten' => 'Blora   ', 'provinsi_id_provinsi' =>33],
            ['id_kabupaten'=>   206, 'nama_kabupaten' => 'Rembang ', 'provinsi_id_provinsi' =>33],
            ['id_kabupaten'=>   207, 'nama_kabupaten' => 'Pati    ', 'provinsi_id_provinsi' =>33],
            ['id_kabupaten'=>   208, 'nama_kabupaten' => 'Kudus   ', 'provinsi_id_provinsi' =>33],
            ['id_kabupaten'=>   209, 'nama_kabupaten' => 'Jepara  ', 'provinsi_id_provinsi' =>33],
            ['id_kabupaten'=>   210, 'nama_kabupaten' => 'Demak   ', 'provinsi_id_provinsi' =>33],
            ['id_kabupaten'=>   211, 'nama_kabupaten' => 'Semarang  ', 'provinsi_id_provinsi' =>33],
            ['id_kabupaten'=>   212, 'nama_kabupaten' => 'Temanggung', 'provinsi_id_provinsi' =>33],
            ['id_kabupaten'=>   213, 'nama_kabupaten' => 'Kendal  ', 'provinsi_id_provinsi' =>33],
            ['id_kabupaten'=>   214, 'nama_kabupaten' => 'Batang  ', 'provinsi_id_provinsi' =>33],
            ['id_kabupaten'=>   215, 'nama_kabupaten' => 'Pekalongan ', 'provinsi_id_provinsi' =>33],
            ['id_kabupaten'=>   216, 'nama_kabupaten' => 'Pemalang', 'provinsi_id_provinsi' =>33],
            ['id_kabupaten'=>   217, 'nama_kabupaten' => 'Tegal   ', 'provinsi_id_provinsi' =>33],
            ['id_kabupaten'=>   218, 'nama_kabupaten' => 'Brebes  ', 'provinsi_id_provinsi' =>33],
            ['id_kabupaten'=>   219, 'nama_kabupaten' => 'Kota Magelang', 'provinsi_id_provinsi' =>   33],
            ['id_kabupaten'=>   220, 'nama_kabupaten' => 'Kota Surakarta', 'provinsi_id_provinsi' =>  33],
            ['id_kabupaten'=>   221, 'nama_kabupaten' => 'Kota Salatiga', 'provinsi_id_provinsi' =>   33],
            ['id_kabupaten'=>   222, 'nama_kabupaten' => 'Kota Semarang', 'provinsi_id_provinsi' =>   33],
            ['id_kabupaten'=>   223, 'nama_kabupaten' => 'Kota Pekalongan', 'provinsi_id_provinsi' => 33],
            ['id_kabupaten'=>   224, 'nama_kabupaten' => 'Kota Tegal', 'provinsi_id_provinsi' =>  33],
            ['id_kabupaten'=>   225, 'nama_kabupaten' => 'Kulon Progo', 'provinsi_id_provinsi' => 34],
            ['id_kabupaten'=>   226, 'nama_kabupaten' => 'Bantul  ', 'provinsi_id_provinsi'   =>34],
            ['id_kabupaten'=>   227, 'nama_kabupaten' => 'Gunung Kidul', 'provinsi_id_provinsi' =>  34],
            ['id_kabupaten'=>   228, 'nama_kabupaten' => 'Sleman  ', 'provinsi_id_provinsi' =>34],
            ['id_kabupaten'=>   229, 'nama_kabupaten' => 'Kota Yogyakarta', 'provinsi_id_provinsi' => 34],
            ['id_kabupaten'=>   230, 'nama_kabupaten' => 'Pacitan', 'provinsi_id_provinsi' =>35],
            ['id_kabupaten'=>   231, 'nama_kabupaten' => 'Ponorogo', 'provinsi_id_provinsi' =>35],        
            ['id_kabupaten'=>   232, 'nama_kabupaten' => 'Trenggalek', 'provinsi_id_provinsi' =>35],
            ['id_kabupaten'=>   233, 'nama_kabupaten' => 'Tulungagung', 'provinsi_id_provinsi' =>35],
            ['id_kabupaten'=>   234, 'nama_kabupaten' => 'Blitar', 'provinsi_id_provinsi' =>35],
            ['id_kabupaten'=>   235, 'nama_kabupaten' => 'Kediri', 'provinsi_id_provinsi' =>35],
            ['id_kabupaten'=>   236, 'nama_kabupaten' => 'Malang', 'provinsi_id_provinsi' =>35],
            ['id_kabupaten'=>   237, 'nama_kabupaten' => 'Lumajang', 'provinsi_id_provinsi' =>35],
            ['id_kabupaten'=>   238, 'nama_kabupaten' => 'Jember', 'provinsi_id_provinsi' =>35],
            ['id_kabupaten'=>   239, 'nama_kabupaten' => 'Banyuwangi', 'provinsi_id_provinsi' =>35],
            ['id_kabupaten'=>   240, 'nama_kabupaten' => 'Bondowoso', 'provinsi_id_provinsi' =>35],
            ['id_kabupaten'=>   241, 'nama_kabupaten' => 'Situbondo', 'provinsi_id_provinsi' =>35],
            ['id_kabupaten'=>   242, 'nama_kabupaten' => 'Probolinggo ', 'provinsi_id_provinsi' =>35],
            ['id_kabupaten'=>   243, 'nama_kabupaten' => 'Pasuruan', 'provinsi_id_provinsi' =>35],
            ['id_kabupaten'=>   244, 'nama_kabupaten' => 'Sidoarjo', 'provinsi_id_provinsi' =>35],
            ['id_kabupaten'=>   245, 'nama_kabupaten' => 'Mojokerto', 'provinsi_id_provinsi' =>35],
            ['id_kabupaten'=>   246, 'nama_kabupaten' => 'Jombang', 'provinsi_id_provinsi' =>35],
            ['id_kabupaten'=>   247, 'nama_kabupaten' => 'Nganjuk', 'provinsi_id_provinsi' =>35],
            ['id_kabupaten'=>   248, 'nama_kabupaten' => 'Madiun', 'provinsi_id_provinsi' =>35],
            ['id_kabupaten'=>   249, 'nama_kabupaten' => 'Magetan', 'provinsi_id_provinsi' =>35],
            ['id_kabupaten'=>   250, 'nama_kabupaten' => 'Ngawi', 'provinsi_id_provinsi' =>35],
            ['id_kabupaten'=>   251, 'nama_kabupaten' => 'Bojonegoro ', 'provinsi_id_provinsi' =>35],
            ['id_kabupaten'=>   252, 'nama_kabupaten' => 'Tuban', 'provinsi_id_provinsi' =>35],
            ['id_kabupaten'=>   253, 'nama_kabupaten' => 'Lamongan', 'provinsi_id_provinsi' =>35],
            ['id_kabupaten'=>   254, 'nama_kabupaten' => 'Gresik', 'provinsi_id_provinsi' =>35],
            ['id_kabupaten'=>   255, 'nama_kabupaten' => 'Bangkalan ', 'provinsi_id_provinsi' =>35],
            ['id_kabupaten'=>   256, 'nama_kabupaten' => 'Sampang', 'provinsi_id_provinsi' =>35],
            ['id_kabupaten'=>   257, 'nama_kabupaten' => 'Pamekasan  ', 'provinsi_id_provinsi' =>35],
            ['id_kabupaten'=>   258, 'nama_kabupaten' => 'Sumenep', 'provinsi_id_provinsi' =>35],
            ['id_kabupaten'=>   259, 'nama_kabupaten' => 'Kota Kediri', 'provinsi_id_provinsi' => 35],
            ['id_kabupaten'=>   260, 'nama_kabupaten' => 'Kota Blitar', 'provinsi_id_provinsi' => 35],
            ['id_kabupaten'=>   261, 'nama_kabupaten' => 'Kota Malang', 'provinsi_id_provinsi' => 35],
            ['id_kabupaten'=>   262, 'nama_kabupaten' => 'Kota Probolinggo', 'provinsi_id_provinsi'=> 35],
            ['id_kabupaten'=>   263, 'nama_kabupaten' => 'Kota Pasuruan', 'provinsi_id_provinsi' =>   35],
            ['id_kabupaten'=>   264, 'nama_kabupaten' => 'Kota Mojokerto', 'provinsi_id_provinsi' =>  35],
            ['id_kabupaten'=>   265, 'nama_kabupaten' => 'Kota Madiun', 'provinsi_id_provinsi'     => 35],
            ['id_kabupaten'=>   266, 'nama_kabupaten' => 'Kota Surabaya', 'provinsi_id_provinsi' =>   35],
            ['id_kabupaten'=>   267, 'nama_kabupaten' => 'Kota Batu', 'provinsi_id_provinsi' =>   35],
            ['id_kabupaten'=>   268, 'nama_kabupaten' => 'Pandeglang', 'provinsi_id_provinsi' =>36],
            ['id_kabupaten'=>   269, 'nama_kabupaten' => 'Lebak', 'provinsi_id_provinsi'     =>36],
            ['id_kabupaten'=>   270, 'nama_kabupaten' => 'Tangerang ', 'provinsi_id_provinsi'   =>36],
            ['id_kabupaten'=>   271, 'nama_kabupaten' => 'Serang ', 'provinsi_id_provinsi'     =>36],
            ['id_kabupaten'=>   272, 'nama_kabupaten' => 'Kota Tangerang', 'provinsi_id_provinsi' =>  36],
            ['id_kabupaten'=>   273, 'nama_kabupaten' => 'Kota Cilegon', 'provinsi_id_provinsi' =>    36],
            ['id_kabupaten'=>   274, 'nama_kabupaten' => 'Kota Serang', 'provinsi_id_provinsi'     => 36],
            ['id_kabupaten'=>   275, 'nama_kabupaten' => 'Kota Tangerang Selatan', 'provinsi_id_provinsi' => 36],            
            ['id_kabupaten'=>   276, 'nama_kabupaten' => 'Jembrana', 'provinsi_id_provinsi' =>51],
            ['id_kabupaten'=>   277, 'nama_kabupaten' => 'Tabanan', 'provinsi_id_provinsi' =>51],
            ['id_kabupaten'=>   278, 'nama_kabupaten' => 'Badung', 'provinsi_id_provinsi' => 51],
            ['id_kabupaten'=>   279, 'nama_kabupaten' => 'Gianyar', 'provinsi_id_provinsi' => 51],
            ['id_kabupaten'=>   280, 'nama_kabupaten' => 'Klungkung   ', 'provinsi_id_provinsi' => 51],
            ['id_kabupaten'=>   281, 'nama_kabupaten' => 'Bangli', 'provinsi_id_provinsi' =>51],
            ['id_kabupaten'=>   282, 'nama_kabupaten' => 'Karang Asem', 'provinsi_id_provinsi' => 51],
            ['id_kabupaten'=>   283, 'nama_kabupaten' => 'Buleleng', 'provinsi_id_provinsi' =>51],
            ['id_kabupaten'=>   284, 'nama_kabupaten' => 'Kota Denpasar', 'provinsi_id_provinsi' =>   51],
            ['id_kabupaten'=>   285, 'nama_kabupaten' => 'Lombok Barat', 'provinsi_id_provinsi' =>    52],
            ['id_kabupaten'=>   286, 'nama_kabupaten' => 'Lombok Tengah', 'provinsi_id_provinsi' =>   52],
            ['id_kabupaten'=>   287, 'nama_kabupaten' => 'Lombok Timur', 'provinsi_id_provinsi' =>    52],
            ['id_kabupaten'=>   288, 'nama_kabupaten' => 'Sumbawa', 'provinsi_id_provinsi'  =>     52],
            ['id_kabupaten'=>   289, 'nama_kabupaten' => 'Dompu', 'provinsi_id_provinsi' =>52],
            ['id_kabupaten'=>   290, 'nama_kabupaten' => 'Bima', 'provinsi_id_provinsi' =>52],
            ['id_kabupaten'=>   291, 'nama_kabupaten' => 'Sumbawa Barat', 'provinsi_id_provinsi' =>   52],
            ['id_kabupaten'=>   292, 'nama_kabupaten' => 'Lombok Utara', 'provinsi_id_provinsi' =>    52],
            ['id_kabupaten'=>   293, 'nama_kabupaten' => 'Kota Mataram', 'provinsi_id_provinsi' =>    52],
            ['id_kabupaten'=>   294, 'nama_kabupaten' => 'Kota Bima', 'provinsi_id_provinsi' =>   52],
            ['id_kabupaten'=>   295, 'nama_kabupaten' => 'Kupang', 'provinsi_id_provinsi' => 53],
            ['id_kabupaten'=>   296, 'nama_kabupaten' => 'Timor Tengah Selatan', 'provinsi_id_provinsi' => 53],
            ['id_kabupaten'=>   297, 'nama_kabupaten' => 'Timor Tengah Utara', 'provinsi_id_provinsi' => 53],
            ['id_kabupaten'=>   298, 'nama_kabupaten' => 'Belu', 'provinsi_id_provinsi' =>53],
            ['id_kabupaten'=>   299, 'nama_kabupaten' => 'Alor', 'provinsi_id_provinsi' =>53],
            ['id_kabupaten'=>   300, 'nama_kabupaten' => 'Flores Timur', 'provinsi_id_provinsi' =>53],
            ['id_kabupaten'=>   301, 'nama_kabupaten' => 'Sikka', 'provinsi_id_provinsi' =>53],
            ['id_kabupaten'=>   302, 'nama_kabupaten' => 'Ende', 'provinsi_id_provinsi' =>53],
            ['id_kabupaten'=>   303, 'nama_kabupaten' => 'Ngada', 'provinsi_id_provinsi' =>53],
            ['id_kabupaten'=>   304, 'nama_kabupaten' => 'Manggarai', 'provinsi_id_provinsi' =>53],
            ['id_kabupaten'=>   305, 'nama_kabupaten' => 'Sumba Barat', 'provinsi_id_provinsi' => 53],
            ['id_kabupaten'=>   306, 'nama_kabupaten' => 'Sumba Timur', 'provinsi_id_provinsi' => 53],
            ['id_kabupaten'=>   307, 'nama_kabupaten' => 'Lembata', 'provinsi_id_provinsi' => 53],
            ['id_kabupaten'=>   308, 'nama_kabupaten' => 'Rote Ndao', 'provinsi_id_provinsi' =>   53],
            ['id_kabupaten'=>   309, 'nama_kabupaten' => 'Manggarai Barat', 'provinsi_id_provinsi' => 53],
            ['id_kabupaten'=>   310, 'nama_kabupaten' => 'Nagekeo', 'provinsi_id_provinsi' =>53],
            ['id_kabupaten'=>   311, 'nama_kabupaten' => 'Sumba Tengah', 'provinsi_id_provinsi' =>    53],
            ['id_kabupaten'=>   312, 'nama_kabupaten' => 'Sumba Barat Daya', 'provinsi_id_provinsi' => 53],
            ['id_kabupaten'=>   313, 'nama_kabupaten' => 'Manggarai Timur', 'provinsi_id_provinsi' => 53],
            ['id_kabupaten'=>   314, 'nama_kabupaten' => 'Sabu Raijua', 'provinsi_id_provinsi' => 53],
            ['id_kabupaten'=>   315, 'nama_kabupaten' => 'Malaka', 'provinsi_id_provinsi' =>53],
            ['id_kabupaten'=>   316, 'nama_kabupaten' => 'Kota Kupang', 'provinsi_id_provinsi' => 53],
            ['id_kabupaten'=>   317, 'nama_kabupaten' => 'Sambas', 'provinsi_id_provinsi' =>61],
            ['id_kabupaten'=>   318, 'nama_kabupaten' => 'Mempawah', 'provinsi_id_provinsi' =>61],
            ['id_kabupaten'=>   319, 'nama_kabupaten' => 'Sanggau', 'provinsi_id_provinsi' =>61],
            ['id_kabupaten'=>   320, 'nama_kabupaten' => 'Ketapang', 'provinsi_id_provinsi' =>61],
            ['id_kabupaten'=>   321, 'nama_kabupaten' => 'Sintang', 'provinsi_id_provinsi' =>61],
            ['id_kabupaten'=>   322, 'nama_kabupaten' => 'Kapuas Hulu', 'provinsi_id_provinsi' => 61],
            ['id_kabupaten'=>   323, 'nama_kabupaten' => 'Bengkayang', 'provinsi_id_provinsi' =>61],
            ['id_kabupaten'=>   324, 'nama_kabupaten' => 'Landak', 'provinsi_id_provinsi' =>61],
            ['id_kabupaten'=>   325, 'nama_kabupaten' => 'Melawi', 'provinsi_id_provinsi' =>61],
            ['id_kabupaten'=>   326, 'nama_kabupaten' => 'Sekadau', 'provinsi_id_provinsi' =>61],
            ['id_kabupaten'=>   327, 'nama_kabupaten' => 'Kayong Utara', 'provinsi_id_provinsi' =>61],
            ['id_kabupaten'=>   328, 'nama_kabupaten' => 'Kubu Raya', 'provinsi_id_provinsi' =>   61],
            ['id_kabupaten'=>   329, 'nama_kabupaten' => 'Kota Pontianak', 'provinsi_id_provinsi' =>  61],
            ['id_kabupaten'=>   330, 'nama_kabupaten' => 'Kota Singkawang', 'provinsi_id_provinsi' => 61],
            ['id_kabupaten'=>   331, 'nama_kabupaten' => 'Kotawaringin Barat', 'provinsi_id_provinsi' =>  62],
            ['id_kabupaten'=>   332, 'nama_kabupaten' => 'Kotawaringin Timur', 'provinsi_id_provinsi' =>  62],
            ['id_kabupaten'=>   333, 'nama_kabupaten' => 'Kapuas', 'provinsi_id_provinsi' =>62],
            ['id_kabupaten'=>   334, 'nama_kabupaten' => 'Barito Selatan', 'provinsi_id_provinsi' =>  62],
            ['id_kabupaten'=>   335, 'nama_kabupaten' => 'Barito Utara', 'provinsi_id_provinsi' =>    62],
            ['id_kabupaten'=>   336, 'nama_kabupaten' => 'Katingan', 'provinsi_id_provinsi' =>62],
            ['id_kabupaten'=>   337, 'nama_kabupaten' => 'Seruyan', 'provinsi_id_provinsi' =>62],
            ['id_kabupaten'=>   338, 'nama_kabupaten' => 'Sukamara', 'provinsi_id_provinsi' =>62],
            ['id_kabupaten'=>   339, 'nama_kabupaten' => 'Lamandau', 'provinsi_id_provinsi' =>62],
            ['id_kabupaten'=>   340, 'nama_kabupaten' => 'Gunung Mas', 'provinsi_id_provinsi' =>  62],
            ['id_kabupaten'=>   341, 'nama_kabupaten' => 'Pulang Pisau', 'provinsi_id_provinsi' =>    62],
            ['id_kabupaten'=>   342, 'nama_kabupaten' => 'Murung Raya', 'provinsi_id_provinsi' => 62],
            ['id_kabupaten'=>   343, 'nama_kabupaten' => 'Barito Timur', 'provinsi_id_provinsi' =>    62],
            ['id_kabupaten'=>   344, 'nama_kabupaten' => 'Kota Palangka Raya', 'provinsi_id_provinsi' => 62],
            ['id_kabupaten'=>   345, 'nama_kabupaten' => 'Tanah Laut', 'provinsi_id_provinsi' =>  63],
            ['id_kabupaten'=>   346, 'nama_kabupaten' => 'Kota Baru', 'provinsi_id_provinsi' =>   63],
            ['id_kabupaten'=>   347, 'nama_kabupaten' => 'Banjar', 'provinsi_id_provinsi' =>63],
            ['id_kabupaten'=>   348, 'nama_kabupaten' => 'Barito Kuala', 'provinsi_id_provinsi' =>    63],
            ['id_kabupaten'=>   349, 'nama_kabupaten' => 'Tapin', 'provinsi_id_provinsi' =>63],
            ['id_kabupaten'=>   350, 'nama_kabupaten' => 'Hulu Sungai Selatan', 'provinsi_id_provinsi' => 63], 
            ['id_kabupaten'=>   351, 'nama_kabupaten' => 'Hulu Sungai Tengah', 'provinsi_id_provinsi' => 63],  
            ['id_kabupaten'=>   352, 'nama_kabupaten' => 'Hulu Sungai Utara', 'provinsi_id_provinsi' => 63],   
            ['id_kabupaten'=>   353, 'nama_kabupaten' => 'Tabalong', 'provinsi_id_provinsi' =>63],
            ['id_kabupaten'=>   354, 'nama_kabupaten' => 'Tanah Bumbu', 'provinsi_id_provinsi' => 63],
            ['id_kabupaten'=>   355, 'nama_kabupaten' => 'Balangan', 'provinsi_id_provinsi' =>63],
            ['id_kabupaten'=>   356, 'nama_kabupaten' => 'Kota Banjarmasin', 'provinsi_id_provinsi' =>63],
            ['id_kabupaten'=>   357, 'nama_kabupaten' => 'Kota Banjar Baru', 'provinsi_id_provinsi' =>63],
            ['id_kabupaten'=>   358, 'nama_kabupaten' => 'Paser', 'provinsi_id_provinsi' =>64],
            ['id_kabupaten'=>   359, 'nama_kabupaten' => 'Kutai Kartanegara', 'provinsi_id_provinsi' =>   64],
            ['id_kabupaten'=>   360, 'nama_kabupaten' => 'Berau', 'provinsi_id_provinsi' =>64],
            ['id_kabupaten'=>   361, 'nama_kabupaten' => 'Kutai Barat', 'provinsi_id_provinsi' => 64],
            ['id_kabupaten'=>   362, 'nama_kabupaten' => 'Kutai Timur', 'provinsi_id_provinsi' => 64],
            ['id_kabupaten'=>   363, 'nama_kabupaten' => 'Penajam Paser Utara', 'provinsi_id_provinsi' => 64],
            ['id_kabupaten'=>   364, 'nama_kabupaten' => 'Mahakam Hulu', 'provinsi_id_provinsi' =>    64],
            ['id_kabupaten'=>   365, 'nama_kabupaten' => 'Kota Balikpapan', 'provinsi_id_provinsi' => 64],
            ['id_kabupaten'=>   366, 'nama_kabupaten' => 'Kota Samarinda', 'provinsi_id_provinsi' =>  64],
            ['id_kabupaten'=>   367, 'nama_kabupaten' => 'Kota Bontang', 'provinsi_id_provinsi' =>    64],
            ['id_kabupaten'=>   368, 'nama_kabupaten' => 'Bulungan', 'provinsi_id_provinsi' =>65],
            ['id_kabupaten'=>   369, 'nama_kabupaten' => 'Malinau', 'provinsi_id_provinsi' =>65],
            ['id_kabupaten'=>   370, 'nama_kabupaten' => 'Nunukan', 'provinsi_id_provinsi' =>65],
            ['id_kabupaten'=>   371, 'nama_kabupaten' => 'Tana Tidung', 'provinsi_id_provinsi' => 65],
            ['id_kabupaten'=>   372, 'nama_kabupaten' => 'Kota Tarakan', 'provinsi_id_provinsi' =>    65],
            ['id_kabupaten'=>   373, 'nama_kabupaten' => 'Bolaang Mongondow', 'provinsi_id_provinsi' =>   71],
            ['id_kabupaten'=>   374, 'nama_kabupaten' => 'Minahasa', 'provinsi_id_provinsi' => 71],
            ['id_kabupaten'=>   375, 'nama_kabupaten' => 'Kepulauan Sangihe', 'provinsi_id_provinsi' =>   71],
            ['id_kabupaten'=>   376, 'nama_kabupaten' => 'Kepulauan Talaud', 'provinsi_id_provinsi' =>    71],
            ['id_kabupaten'=>   377, 'nama_kabupaten' => 'Minahasa Selatan', 'provinsi_id_provinsi' =>    71],
            ['id_kabupaten'=>   378, 'nama_kabupaten' => 'Minahasa Utara', 'provinsi_id_provinsi' =>  71],
            ['id_kabupaten'=>   379, 'nama_kabupaten' => 'Bolaang Mongondow Utara', 'provinsi_id_provinsi' => 71],
            ['id_kabupaten'=>   380, 'nama_kabupaten' => 'Minahasa Tenggara', 'provinsi_id_provinsi' =>   71],
            ['id_kabupaten'=>   381, 'nama_kabupaten' => 'Siau Tagulandang Biaro', 'provinsi_id_provinsi' => 71],
            ['id_kabupaten'=>   382, 'nama_kabupaten' => 'Bolaang Mongondow Timur', 'provinsi_id_provinsi' => 71],
            ['id_kabupaten'=>   383, 'nama_kabupaten' => 'Bolaang Mongondow Selatan', 'provinsi_id_provinsi' => 71],
            ['id_kabupaten'=>   384, 'nama_kabupaten' => 'Kota Manado', 'provinsi_id_provinsi' => 71],
            ['id_kabupaten'=>   385, 'nama_kabupaten' => 'Kota Bitung', 'provinsi_id_provinsi' => 71],
            ['id_kabupaten'=>   386, 'nama_kabupaten' => 'Kota Tomohon', 'provinsi_id_provinsi' => 71],
            ['id_kabupaten'=>   387, 'nama_kabupaten' => 'Kota Kotamobagu', 'provinsi_id_provinsi' => 71],
            ['id_kabupaten'=>   388, 'nama_kabupaten' => 'Banggai', 'provinsi_id_provinsi' =>72],
            ['id_kabupaten'=>   389, 'nama_kabupaten' => 'Poso', 'provinsi_id_provinsi' =>72],
            ['id_kabupaten'=>   390, 'nama_kabupaten' => 'Donggala', 'provinsi_id_provinsi' =>72],
            ['id_kabupaten'=>   391, 'nama_kabupaten' => 'Toli-Toli', 'provinsi_id_provinsi' =>   72],
            ['id_kabupaten'=>   392, 'nama_kabupaten' => 'Buol', 'provinsi_id_provinsi' =>  72],
            ['id_kabupaten'=>   393, 'nama_kabupaten' => 'Morowali', 'provinsi_id_provinsi' =>72],
            ['id_kabupaten'=>   394, 'nama_kabupaten' => 'Morowali Utara', 'provinsi_id_provinsi' =>  72],
            ['id_kabupaten'=>   395, 'nama_kabupaten' => 'Banggai Laut', 'provinsi_id_provinsi' =>    72],
            ['id_kabupaten'=>   396, 'nama_kabupaten' => 'Banggai Kepulauan', 'provinsi_id_provinsi' =>   72],
            ['id_kabupaten'=>   397, 'nama_kabupaten' => 'Parigi Moutong', 'provinsi_id_provinsi' =>  72],
            ['id_kabupaten'=>   398, 'nama_kabupaten' => 'Tojo Una-Una', 'provinsi_id_provinsi' =>72],
            ['id_kabupaten'=>   399, 'nama_kabupaten' => 'Sigi', 'provinsi_id_provinsi' =>72],
            ['id_kabupaten'=>   400, 'nama_kabupaten' => 'Kota Palu', 'provinsi_id_provinsi' =>   72],
            ['id_kabupaten'=>   401, 'nama_kabupaten' => 'Kepulauan Selayar', 'provinsi_id_provinsi' =>   73],
            ['id_kabupaten'=>   402, 'nama_kabupaten' => 'Bulukumba', 'provinsi_id_provinsi' =>73],
            ['id_kabupaten'=>   403, 'nama_kabupaten' => 'Bantaeng', 'provinsi_id_provinsi' =>73],
            ['id_kabupaten'=>   404, 'nama_kabupaten' => 'Jeneponto', 'provinsi_id_provinsi' =>73],
            ['id_kabupaten'=>   405, 'nama_kabupaten' => 'Takalar', 'provinsi_id_provinsi' =>73],
            ['id_kabupaten'=>   406, 'nama_kabupaten' => 'Gowa', 'provinsi_id_provinsi' =>73],
            ['id_kabupaten'=>   407, 'nama_kabupaten' => 'Sinjai', 'provinsi_id_provinsi' =>73],
            ['id_kabupaten'=>   408, 'nama_kabupaten' => 'Bone', 'provinsi_id_provinsi' =>73],
            ['id_kabupaten'=>   409, 'nama_kabupaten' => 'Maros', 'provinsi_id_provinsi' =>73],
            ['id_kabupaten'=>   410, 'nama_kabupaten' => 'Pangkajene Dan Kepulauan', 'provinsi_id_provinsi' => 73],
            ['id_kabupaten'=>   411, 'nama_kabupaten' => 'Barru', 'provinsi_id_provinsi' =>73],
            ['id_kabupaten'=>   412, 'nama_kabupaten' => 'Soppeng', 'provinsi_id_provinsi' =>73],
            ['id_kabupaten'=>   413, 'nama_kabupaten' => 'Wajo', 'provinsi_id_provinsi' =>73],
            ['id_kabupaten'=>   414, 'nama_kabupaten' => 'Sidenreng Rappang', 'provinsi_id_provinsi' =>   73],
            ['id_kabupaten'=>   415, 'nama_kabupaten' => 'Pinrang', 'provinsi_id_provinsi' =>73],
            ['id_kabupaten'=>   416, 'nama_kabupaten' => 'Enrekang', 'provinsi_id_provinsi' =>73],
            ['id_kabupaten'=>   417, 'nama_kabupaten' => 'Luwu', 'provinsi_id_provinsi' =>73],
            ['id_kabupaten'=>   418, 'nama_kabupaten' => 'Tana Toraja', 'provinsi_id_provinsi' => 73],
            ['id_kabupaten'=>   419, 'nama_kabupaten' => 'Toraja Utara', 'provinsi_id_provinsi' =>    73],
            ['id_kabupaten'=>   420, 'nama_kabupaten' => 'Luwu Utara', 'provinsi_id_provinsi' =>  73],
            ['id_kabupaten'=>   421, 'nama_kabupaten' => 'Luwu Timur', 'provinsi_id_provinsi' =>  73],
            ['id_kabupaten'=>   422, 'nama_kabupaten' => 'Kota Makassar', 'provinsi_id_provinsi' =>   73],
            ['id_kabupaten'=>   423, 'nama_kabupaten' => 'Kota Parepare', 'provinsi_id_provinsi' =>   73],
            ['id_kabupaten'=>   424, 'nama_kabupaten' => 'Kota Palopo', 'provinsi_id_provinsi' => 73],
            ['id_kabupaten'=>   425, 'nama_kabupaten' => 'Kolaka', 'provinsi_id_provinsi' =>74],
            ['id_kabupaten'=>   426, 'nama_kabupaten' => 'Konawe', 'provinsi_id_provinsi' =>74],
            ['id_kabupaten'=>   427, 'nama_kabupaten' => 'Konawe Kepulauan', 'provinsi_id_provinsi' =>    74],
            ['id_kabupaten'=>   428, 'nama_kabupaten' => 'Muna', 'provinsi_id_provinsi' =>74],
            ['id_kabupaten'=>   429, 'nama_kabupaten' => 'Buton', 'provinsi_id_provinsi' =>74],
            ['id_kabupaten'=>   430, 'nama_kabupaten' => 'Konawe Selatan', 'provinsi_id_provinsi' =>  74],
            ['id_kabupaten'=>   431, 'nama_kabupaten' => 'Bombana', 'provinsi_id_provinsi' =>74],
            ['id_kabupaten'=>   432, 'nama_kabupaten' => 'Wakatobi', 'provinsi_id_provinsi' =>74],
            ['id_kabupaten'=>   433, 'nama_kabupaten' => 'Kolaka Utara', 'provinsi_id_provinsi' =>74],
            ['id_kabupaten'=>   434, 'nama_kabupaten' => 'Buton Utara', 'provinsi_id_provinsi' => 74],
            ['id_kabupaten'=>   435, 'nama_kabupaten' => 'Konawe Utara', 'provinsi_id_provinsi' =>74],
            ['id_kabupaten'=>   436, 'nama_kabupaten' => 'Kolaka Timur', 'provinsi_id_provinsi' =>74],
            ['id_kabupaten'=>   437, 'nama_kabupaten' => 'Kota Kendari', 'provinsi_id_provinsi' =>74],
            ['id_kabupaten'=>   438, 'nama_kabupaten' => 'Kota Baubau', 'provinsi_id_provinsi' => 74],
            ['id_kabupaten'=>   439, 'nama_kabupaten' => 'Gorontalo', 'provinsi_id_provinsi' => 75],
            ['id_kabupaten'=>   440, 'nama_kabupaten' => 'Boalemo', 'provinsi_id_provinsi' =>75],
            ['id_kabupaten'=>   441, 'nama_kabupaten' => 'Bone Bolango', 'provinsi_id_provinsi' =>75],
            ['id_kabupaten'=>   442, 'nama_kabupaten' => 'Pohuwato', 'provinsi_id_provinsi' =>75],
            ['id_kabupaten'=>   443, 'nama_kabupaten' => 'Gorontalo Utara', 'provinsi_id_provinsi' => 75],
            ['id_kabupaten'=>   444, 'nama_kabupaten' => 'Kota Gorontalo', 'provinsi_id_provinsi' =>  75],
            ['id_kabupaten'=>   445, 'nama_kabupaten' => 'Mamuju Utara', 'provinsi_id_provinsi' =>    76],
            ['id_kabupaten'=>   446, 'nama_kabupaten' => 'Mamuju', 'provinsi_id_provinsi' =>76],
            ['id_kabupaten'=>   447, 'nama_kabupaten' => 'Mamasa', 'provinsi_id_provinsi' =>76],
            ['id_kabupaten'=>   448, 'nama_kabupaten' => 'Polewali Mandar', 'provinsi_id_provinsi' => 76],
            ['id_kabupaten'=>   449, 'nama_kabupaten' => 'Majene', 'provinsi_id_provinsi' =>76],
            ['id_kabupaten'=>   450, 'nama_kabupaten' => 'Mamuju Tengah', 'provinsi_id_provinsi' =>   76],
            ['id_kabupaten'=>   451, 'nama_kabupaten' => 'Maluku Tengah', 'provinsi_id_provinsi' =>   81],
            ['id_kabupaten'=>   452, 'nama_kabupaten' => 'Maluku Tenggara', 'provinsi_id_provinsi' => 81],
            ['id_kabupaten'=>   453, 'nama_kabupaten' => 'Maluku Tenggara Barat', 'provinsi_id_provinsi' => 81],
            ['id_kabupaten'=>   454, 'nama_kabupaten' => 'Buru', 'provinsi_id_provinsi' =>81],
            ['id_kabupaten'=>   455, 'nama_kabupaten' => 'Seram Bagian Timur', 'provinsi_id_provinsi' => 81], 
            ['id_kabupaten'=>   456, 'nama_kabupaten' => 'Seram Bagian Barat', 'provinsi_id_provinsi' => 81], 
            ['id_kabupaten'=>   457, 'nama_kabupaten' => 'Kepulauan Aru', 'provinsi_id_provinsi' =>   81],
            ['id_kabupaten'=>   458, 'nama_kabupaten' => 'Maluku Barat Daya', 'provinsi_id_provinsi' => 81],
            ['id_kabupaten'=>   459, 'nama_kabupaten' => 'Buru Selatan', 'provinsi_id_provinsi' =>    81],
            ['id_kabupaten'=>   460, 'nama_kabupaten' => 'Kota Ambon', 'provinsi_id_provinsi' =>  81],
            ['id_kabupaten'=>   461, 'nama_kabupaten' => 'Kota Tual', 'provinsi_id_provinsi' =>   81],
            ['id_kabupaten'=>   462, 'nama_kabupaten' => 'Halmahera Barat', 'provinsi_id_provinsi' => 82],
            ['id_kabupaten'=>   463, 'nama_kabupaten' => 'Halmahera Tengah', 'provinsi_id_provinsi' =>    82],
            ['id_kabupaten'=>   464, 'nama_kabupaten' => 'Halmahera Utara', 'provinsi_id_provinsi' => 82],
            ['id_kabupaten'=>   465, 'nama_kabupaten' => 'Halmahera Selatan', 'provinsi_id_provinsi' =>   82],
            ['id_kabupaten'=>   466, 'nama_kabupaten' => 'Kepulauan Sula', 'provinsi_id_provinsi' =>  82],
            ['id_kabupaten'=>   467, 'nama_kabupaten' => 'Halmahera Timur', 'provinsi_id_provinsi' => 82],
            ['id_kabupaten'=>   468, 'nama_kabupaten' => 'Pulau Morotai', 'provinsi_id_provinsi' =>   82],
            ['id_kabupaten'=>   469, 'nama_kabupaten' => 'Pulau Taliabu', 'provinsi_id_provinsi' =>   82],
            ['id_kabupaten'=>   470, 'nama_kabupaten' => 'Kota Ternate', 'provinsi_id_provinsi' =>    82],
            ['id_kabupaten'=>   471, 'nama_kabupaten' => 'Kota Tidore Kepulauan', 'provinsi_id_provinsi' => 82],
            ['id_kabupaten'=>   472, 'nama_kabupaten' => 'Merauke', 'provinsi_id_provinsi' =>91],
            ['id_kabupaten'=>   473, 'nama_kabupaten' => 'Jayawijaya', 'provinsi_id_provinsi' =>91],
            ['id_kabupaten'=>   474, 'nama_kabupaten' => 'Jayapura', 'provinsi_id_provinsi' =>91],
            ['id_kabupaten'=>   475, 'nama_kabupaten' => 'Nabire', 'provinsi_id_provinsi' =>91],
            ['id_kabupaten'=>   476, 'nama_kabupaten' => 'Kepulauan Yapen', 'provinsi_id_provinsi' => 91],
            ['id_kabupaten'=>   477, 'nama_kabupaten' => 'Biak Numfor', 'provinsi_id_provinsi' => 91],
            ['id_kabupaten'=>   478, 'nama_kabupaten' => 'Puncak Jaya', 'provinsi_id_provinsi' => 91],
            ['id_kabupaten'=>   479, 'nama_kabupaten' => 'Paniai', 'provinsi_id_provinsi' =>91],
            ['id_kabupaten'=>   480, 'nama_kabupaten' => 'Mimika', 'provinsi_id_provinsi' =>91],
            ['id_kabupaten'=>   481, 'nama_kabupaten' => 'Sarmi', 'provinsi_id_provinsi' =>91],          
            ['id_kabupaten'=>   482, 'nama_kabupaten' => 'Keerom', 'provinsi_id_provinsi' =>91],
            ['id_kabupaten'=>   483, 'nama_kabupaten' => 'Pegunungan Bintang', 'provinsi_id_provinsi' =>  91],
            ['id_kabupaten'=>   484, 'nama_kabupaten' => 'Yahukimo', 'provinsi_id_provinsi' =>91],
            ['id_kabupaten'=>   485, 'nama_kabupaten' => 'Tolikara', 'provinsi_id_provinsi' =>91],
            ['id_kabupaten'=>   486, 'nama_kabupaten' => 'Waropen', 'provinsi_id_provinsi' =>91],
            ['id_kabupaten'=>   487, 'nama_kabupaten' => 'Boven Digoel', 'provinsi_id_provinsi' =>    91],
            ['id_kabupaten'=>   488, 'nama_kabupaten' => 'Mappi', 'provinsi_id_provinsi' =>91],
            ['id_kabupaten'=>   489, 'nama_kabupaten' => 'Asmat', 'provinsi_id_provinsi' =>91],
            ['id_kabupaten'=>   490, 'nama_kabupaten' => 'Lanny Jaya', 'provinsi_id_provinsi' =>  91],
            ['id_kabupaten'=>   491, 'nama_kabupaten' => 'Nduga', 'provinsi_id_provinsi' =>91],
            ['id_kabupaten'=>   492, 'nama_kabupaten' => 'Supiori', 'provinsi_id_provinsi' =>91],
            ['id_kabupaten'=>   493, 'nama_kabupaten' => 'Intan Jaya', 'provinsi_id_provinsi' => 91],
            ['id_kabupaten'=>   494, 'nama_kabupaten' => 'Puncak', 'provinsi_id_provinsi' =>91],
            ['id_kabupaten'=>   495, 'nama_kabupaten' => 'Deiyai', 'provinsi_id_provinsi' =>91],
            ['id_kabupaten'=>   496, 'nama_kabupaten' => 'Dogiyai', 'provinsi_id_provinsi' =>91],
            ['id_kabupaten'=>   497, 'nama_kabupaten' => 'Yalimo', 'provinsi_id_provinsi' =>91],
            ['id_kabupaten'=>   498, 'nama_kabupaten' => 'Mamberamo Tengah', 'provinsi_id_provinsi' =>    91],
            ['id_kabupaten'=>   499, 'nama_kabupaten' => 'Mamberamo Raya', 'provinsi_id_provinsi' =>  91],
            ['id_kabupaten'=>   500, 'nama_kabupaten' => 'Kota Jayapura', 'provinsi_id_provinsi' =>   91],
            ['id_kabupaten'=>   501, 'nama_kabupaten' => 'Sorong', 'provinsi_id_provinsi' =>92],
            ['id_kabupaten'=>   502, 'nama_kabupaten' => 'Manokwari', 'provinsi_id_provinsi' =>92],
            ['id_kabupaten'=>   503, 'nama_kabupaten' => 'Fakfak', 'provinsi_id_provinsi' =>92],
            ['id_kabupaten'=>   504, 'nama_kabupaten' => 'Sorong Selatan', 'provinsi_id_provinsi' =>  92],
            ['id_kabupaten'=>   505, 'nama_kabupaten' => 'Raja Ampat', 'provinsi_id_provinsi' =>  92],
            ['id_kabupaten'=>   506, 'nama_kabupaten' => 'Teluk Bintuni', 'provinsi_id_provinsi' =>   92],
            ['id_kabupaten'=>   507, 'nama_kabupaten' => 'Teluk Wondama', 'provinsi_id_provinsi' =>   92],
            ['id_kabupaten'=>   508, 'nama_kabupaten' => 'Kaimana', 'provinsi_id_provinsi' =>92],
            ['id_kabupaten'=>   509, 'nama_kabupaten' => 'Maybrat', 'provinsi_id_provinsi' =>92],
            ['id_kabupaten'=>   510, 'nama_kabupaten' => 'Tambrauw', 'provinsi_id_provinsi' =>92],
            ['id_kabupaten'=>   511, 'nama_kabupaten' => 'Pegunungan Arfak', 'provinsi_id_provinsi' =>    92],
            ['id_kabupaten'=>   512, 'nama_kabupaten' => 'Manokwari Selatan', 'provinsi_id_provinsi' =>   92],
            ['id_kabupaten'=>   513, 'nama_kabupaten' => 'Kota Sorong', 'provinsi_id_provinsi' => 92],

        ];

        DB::table('kabupaten')->insert($data);


    }
}
